### ISSUE TITLE
synthesizer unable to process german characters

### ISSUE THREAD

**Issue by simteraplications** [padmalcom/Real-Time-Voice-Cloning-German#11] opened 2021-07-27 22:14 UTC
Hi. I recently played with the synthesizer and made other persons say things but i noticed something. It turns out that the synth cant handle the characters ü, ä and ö and instead replaces them with u, a and o respectively. For an example when i type "das ist unhöhflich" it speaks "das ist unhohflich" or similar. Can this bug maybe be fixed? It's really anoying sometimes.

**Comment by padmalcom** [comment] 2021-08-28 18:19
Hi please check If you replaced the symbols.py or added the missing characters to the _characters string.

**Comment by padmalcom** [comment] 2021-09-16 13:50
Hi, I'm closing this one since the issue is obviously related to _characters.

**Closed as completed by padmalcom** 2021-09-16 13:50 UTC

**Comment by Marcophono2** [comment] 2021-10-17 16:59
Same problem here. And I did change the symbols.py

Best regards
Marc

**Comment by Marcophono2** [comment] 2021-10-29 19:10
Okay, I found the solution. Also in synthesizer\hparams.py an adjustment is needed. Replace 
tts_cleaner_names = ["english_cleaners"]
 with
tts_cleaner_names = ["basic_cleaners"]

No need to train again after this bugfix.

Best regards
Marc

**Comment by padmalcom** [comment] 2021-10-29 19:15
Awesome Marc, thanks a lot!
